[server]
port = 8601
address = "localhost"
headless = false
enableCORS = false
enableXsrfProtection = false

[theme]
base = "dark"
primaryColor = "#3B82F6"
backgroundColor = "#020617"
secondaryBackgroundColor = "#0F172A"
textColor = "#F8FAFC"
